spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.138.213.16:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 10.138.213.16
  cache:
    type: redis
    redis:
      time-to-live: 300000
  session:
    store-type: redis

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web # 设置使用http方式传输数据
  sleuth:
    sampler:
      probability: 1 #采样值介于0-1之间，1则表示全部采样

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 9300

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true





alibaba:
  cloud:
    access-key: xxxxxxxxxxxxxx
    secret-key: xxxxxxxxxxxxxxx
    oss:
      endpoint: oss-cn-guangzhou.aliyuncs.com
logging:
  level:
    com.whut.gulimall: error


