server:
  port: 9700
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  redis:
    host: 10.138.213.16
    port: 6379

  thymeleaf:
    cache: false
  session:
    store-type: redis

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1 #采样值介于0-1之间，1则表示全部采样

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
