server:
  port: 9900
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  redis:
    host: 10.138.213.16

  session:
    store-type: redis

  rabbitmq:
    host: 10.138.213.16
    virtual-host: /

  thymeleaf:
    cache: false

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false # 关闭服务发现，否则spring-cloud会把zipkin的url当作服务名称
    sender:
      type: web # 设置使用http方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

