server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  mail:
    host: smtp.qq.com
    username: 1184384017@qq.com
    password: cklcnowcnkqgfgjf

